### ISSUE TITLE
Using a function (with arguments) for attr_getter

### ISSUE THREAD

**Issue by siddhantgoel** [voidfiles/strainer#4]
Hey, very nice library. I've been looking for a faster alternative to marshmallow and really like using strainer instead.

I've been moving some old code over to using strainer and had a question.

The default value for `attr_getter` is `operator.attrgetter`. In case the original field is a function instead of a property, I could use `operator.methodcall`. What if that function expects an argument?

Consider the following class -

```python
class ChatRoom:
  def unseen_messages_count(self, user):
    return depends_on_the(user)
```

Here the `unseen_messages_count` function returns a different value depending on what `user` is. Is there some way to serialize this? If `attr_getter` would somehow make use of the `context` variable, I could just put the `user` object into the context and then strainer would use it when serializing. But since that's not the case, what's the best way of doing this?

**Comment by voidfiles** [comment]
Sorry, I didn't respond sooner. I don't think there is a good way to handle this using strainer. You might want to think about passing the user to an init function and storing it as a property of class.

**Comment by siddhantgoel** [comment]
For the specific scenario I had in mind, storing it as a property unfortunately wouldn't work. Thanks for the reply anyway!
